CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(

BOARD_ID NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
BOARD_TITLE VARCHAR(500) NOT NULL,
BOARD_WRITER VARCHAR(500) NOT NULL,
BOARD_CONTENT VARCHAR(1000) NOT NULL,
BOARD_REGISTER_DATE DATE DEFAULT SYSDATE,
BOARD_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_BOARD;